version: "3.7"
services:
  gochain-iconee:
    container_name: gochain-iconee
    image: debendraoli/gochain-icon:latest
    env_file:
      - ./gochain-local/data/dockerenv/iconee
    volumes:
      - ./gochain-local/data:/testsuite/data
      - ./gochain-local/chain:/testsuite/chain
    ports:
      - "9082:9082"